### ISSUE TITLE
Crawling Error

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-backend#10]
A minor bug at the `classroom` parsing is discovered.
After crawling of *2018-1학기*, I found there is a `classroom` instance whose fields are,
```python3
building = '#017'
room_no = '-108'
```
I think the first character of `room_no` should not be a hyphen.

**Comment by lameinthebox** [comment]
I know it seems strange, but...actually, there exists classroom '#017--108'. Lower ground floor one...maybe...?
