### ISSUE TITLE
REST API Specification: Student

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-backend#11]
The **`Student`** is custom user model that extends default Django `User` model.

Property | Description
----------- | --------------
id | The unique identifier of default Django
username | The unique identifier of `User` model
password | The hashed password of the student
email | The email address of the student
grade | The University year of the student
college | The college which the student attends
department | The department which the student attends
major | The major which the student attends
not_recommends | The courses that the student does not want to take

----------------------------------------------------------------------------------------------------------------
# List Resource
```
students/
```
## Permissions
**Authenticated** user only

## GET
Returns a list of all current students

### Response Example
**Success**
```json
HTTP 200 OK
[
    {
        "college": 3, 
        "department": 42, 
        "email": "user1@snu.ac.kr", 
        "grade": 3, 
        "id": 2, 
        "major": null, 
        "not_recommends": [
            1, 
            3, 
            81, 
            477, 
            998
        ], 
        "password": "pbkdf2_sha256$100000$KDg5h1Qgs6uS$IX/rzNIj+eXvfkGawphAU5ccNBz/QhFMZZFaXZVXfO0=", 
        "username": "user1"
    }, 
    {
        "college": 3, 
        "department": 67, 
        "email": "user2@snu.ac.kr", 
        "grade": 4, 
        "id": 3, 
        "major": 25, 
        "not_recommends": [
            7, 
            18
        ], 
        "password": "pbkdf2_sha256$100000$sPO7y5ADrbah$G3F11OdV92MziU2PPKWmMnB18fxcKHc+6CxLNawvi5s=", 
        "username": "user2"
    }
]
```

**Error**: Authentication fails
```json
HTTP 403 Forbidden
{
    "detail": "Authentication credentials were not provided."
}
```

## POST
Creates a new student and returns the new student instance.

### Params
Param | Description | Required | Note
-- | -- | -- | --
username | Username which identifies the student | O
password | (unhashed) Password of the student | O | Must be unhashed password or validation function will hash the already hashed password again.
email | Email address of the student | O | The host must be 'snu.ac.kr'
grade | University year of the student | O | Must be a integer of 1~4
college | College id of the student | O
department | Department id of the student | X | The department must belong to the college
major | Major id of the student | X | The major must belong to the department
not_recommends | Id list of the courses that the student does not want to take | O | Can be empty list

### Request & Response Example
**Success**
```json
{
    "username": "user3",
    "password": "!Q@W#E$R",
    "email": "user3@snu.ac.kr",
    "grade": 1,
    "college": 1,
    "department": 1,
    "major": null,
    "not_recommends": [
        1,
        4
    ]
}
```
```json
HTTP 201 Created
{
    "id": 4,
    "username": "user3",
    "password": "pbkdf2_sha256$100000$39SzmJ3aKgEl$PPMuA57V8BYvpn85BbxmXdILYHDrhdLu3HpTOWAGZXU=",
    "email": "user3@snu.ac.kr",
    "grade": 1,
    "college": 1,
    "department": 1,
    "major": null,
    "not_recommends": [
        1,
        4
    ]
}
```

**Error**: password validation fails
```json
{
    "username": "user4",
    "password": "asdf",
    "email": "user4@snu.ac.kr",
    "grade": 3,
    "college": 1
}
```
```json
HTTP 400 Bad Request
{
    "password": [
        "This password is too short. It must contain at least 8 characters.",
        "This password is too common."
    ]
}
```

**Error**: Fields requirement fails
```json
{
    "username": "",
    "password": "",
    "email": "",
    "grade": null,
    "college": null,
    "department": null,
    "major": null,
    "not_recommends": []
}
```
```json
HTTP 400 Bad Request
{
    "college": [
        "This field may not be null."
    ],
    "grade": [
        "This field may not be null."
    ],
    "password": [
        "This field may not be blank."
    ],
    "username": [
        "This field may not be blank."
    ],
    "email": [
        "This field may not be blank."
    ]
}
```

----------------------------------------------------------------------------------------------------------------------------
# Instance Resource

```
students/<int:student_id>/
```

## Permissions
Requester should be **Authenticated** and should be _the_ **Student**
In other words, only that student can access to the student's information.

## GET
Returns the student

### Response Example
**Success**
```json
HTTP 200 OK
{
    "id": 2,
    "username": "user1",
    "password": "pbkdf2_sha256$100000$KDg5h1Qgs6uS$IX/rzNIj+eXvfkGawphAU5ccNBz/QhFMZZFaXZVXfO0=",
    "email": "user1@snu.ac.kr",
    "grade": 3,
    "college": 3,
    "department": 42,
    "major": null,
    "not_recommends": [
        1,
        3,
        81,
        477,
        998
    ]
}
```
**Error**: Requester is not the student
```json
HTTP 403 Forbidden
{
    "detail": "You do not have permission to perform this action."
}
```

## PUT
Replace whole information of the student and return the student

### Params
Param | Description | Required | Note
-- | -- | -- | --
username | Username which identifies the student | O
password | (unhashed) Password of the student | O | Must be unhashed password or validation function will hash the already hashed password again.
email | Email address of the student | O | The host must be 'snu.ac.kr'
grade | University year of the student | O | Must be a integer of 1~4
college | College id of the student | O
department | Department id of the student | X | The department must belong to the college
major | Major id of the student | X | The major must belong to the department
not_recommends | Id list of the courses that the student does not want to take | O | Can be empty list

### Request & Response Example
Similar to **List Resource POST**

## PATCH
Update partial information of the student and return the student

### Params
Param | Description | Note
-- | -- | --
username | Username which identifies the student
password | (unhashed) Password of the student | Must be unhashed password or validation function will hash the already hashed password again.
email | Email address of the student | The host must be 'snu.ac.kr'
grade | University year of the student | Must be a integer of 1~4
college | College id of the student
department | Department id of the student | The department must belong to the college
major | Major id of the student | The major must belong to the department
not_recommends | Id list of the courses that the student does not want to take | Can be empty list

### Request & Response Example
**Success**
```json
{
    "email": "user1@snu.ac.kr",
    "grade": 3,
    "major": null,
    "not_recommends": [
        1,
        3,
        81
    ]
}
```
```json
HTTP 200 OK
{
    "id": 2,
    "username": "user1",
    "password": "pbkdf2_sha256$100000$KDg5h1Qgs6uS$IX/rzNIj+eXvfkGawphAU5ccNBz/QhFMZZFaXZVXfO0=",
    "email": "user1@snu.ac.kr",
    "grade": 3,
    "college": 3,
    "department": 42,
    "major": null,
    "not_recommends": [
        1,
        3,
        81
    ]
}
```

## DELETE
Deletes the student.

### Response Example
**Success**
```json
HTTP 204 No Content
```

**Comment by lameinthebox** [comment]
Moved to wiki
