### ISSUE TITLE
Timetable field in Student

### ISSUE THREAD

**Issue by lameinthebox** [SWPP/ttrs-backend#13]
Doesn't each student need a _Timetable_ field that contains the timetable he/she have chosen?
(And a list of timetables bookmarked or received?)

**Comment by holenet** [comment]
Yes, indeed.
This will be a task we have to do from now on.

It will be good to add *read-only* fields to `StudentSerializer`, such as
- **my_timetable**: the current timetable of the student
- **bookmarked_timetables**: list of timetable that the student have bookmarked.
- **received_timetables**: list of timetable that the student have received.

What do you think about this?

**Comment by lameinthebox** [comment]
Seems ok. Plus, timetable model would need two owner fields; one for representing _real owner_ and another for _previous owner_ (in case of received tts). Right?

**Comment by holenet** [comment]
Right.
A *Received* `TimeTable` instance should have two `ForeignKey`s of `Student`.
However, timetables of other types('my' or 'bookmarked') don't need to have two students.
So, It is ideal to make `BaseTimeTable` model and let three subclass to inherit the base class.
But, it will take too much labor to implement and maintain the structure for future works.

As a result, it would be better to just add a `ForeignKey` field to the `TimeTable` model in existance rather than make excessive models.

**Comment by holenet** [comment]
### What should be done
- [x] add `my_timetable` field to `StudentSerializer`
- [x] add `bookmarked_timetables` field to `StudentSerializer`
- [x] add `received_timetables` field to `StudentSerializer`
- [x] add `sender` ForeignKey field to `TimeTable` model

**Comment by lameinthebox** [comment]
Should sender field in model TimeTable be ForeignKey field?
Isn't it enough to be CharField containing sender's username?

**Comment by holenet** [comment]
We may add 'change username' feature in future(or maybe not).
In case of adding the feature, we have to make `sender` field 'ForeignKey' rather than 'CharField'.
It would be safe to make the implementation to cover more cases.

**Comment by lameinthebox** [comment]
Model TimeTable contains type field. I suppose it is used to show whether the timetable is 'mine', 'bookmarked', or 'received'. So, do we still need three timetables fields in StudentSerializer? I think one timetables field containing all timetables is enough.

**Comment by holenet** [comment]
I thought that giving three separated timetables is more helpful for the frontend development.

**Comment by lameinthebox** [comment]
I've made some improvements, please check [https://github.com/SWPP/ttrs-backend/pull/24](url)

**Comment by holenet** [comment]
You can refer an issue or a pull request by hash tag, like this, #24

**Comment by lameinthebox** [comment]
Thanks for ggul tip.

**Comment by holenet** [comment]
Nice!!
