### ISSUE TITLE
Change app names

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-backend#15]
Currently, there are two apps in this project, `crawler`, `ttrs`.
And the root url configuration is like this,
```python3
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('ttrs.urls')),
    path('crawlers/', include('crawler.urls')),
]
```

While `crawler` app has a prefix path `'crawlers/'`, `ttrs` app does not have one.
When I tried to add 'delete tables' view, I got confused where I put this view.
The 'delete tables' view has a same property as the views in `crawler` app, because only admin user has a permission to access the view.
So, I thought 'delete tables' should be in `crawler` app.
However, when I was to edit `urls.py` of `crawler` app, I realized that the url of 'delete tables' will have prefix of `'crawlers/'`. It is so ridiculous.

So, I want to change names of apps and url prefixes, like this,
```python3
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('ttrs/', include('ttrs.urls')),
    path('manager/', include('manage.urls')),
]
```
Add prefix `'ttrs/'` to `ttrs` app, and change name of `crawler` app to `manager`.
Then, the urls of requests will change like this,
```json
/ttrs/students/
/ttrs/courses/3/
/manager/crawler/
/manager/delete-tables/
...
```

What about this?

**Comment by lameinthebox** [comment]
Sure. It looks fine.
