### ISSUE TITLE
Why is the name field unique in the Course model?

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-backend#17]
In the `Course` model, there is a unique field `name`.
But I think unique field should be `code` field because `code` is the definite unique identifier rather than `name`
What do you think about this?

**Comment by lameinthebox** [comment]
Aren't _course_ and _name_ both unique? I don't think there's problem choosing one over another to be unique.

**Comment by holenet** [comment]
There is no `course` field in `Course` model.

**Comment by lameinthebox** [comment]
Sorry, I meant _code_ and _name_.

**Comment by holenet** [comment]
https://github.com/SWPP/ttrs-backend/blob/f1732f0fc42df06a88e7523b2f01d3a6ae4bc9d4/backend/ttrs/models.py#L20-L21
`code` is not unique field.

There is *NO* possibility of that two distinct courses share same *code*.
BUT, There is a *slight* possibility of that two distinct courses share same *name*.
So, I think `unique=True` should be placed in `code` field.

**Comment by lameinthebox** [comment]
영어로 하니까 전달이 잘 안 되네.
코드 필드랑 이름 필드가 지금 유니크하게 되어있다는 말이 아니라 실제 코드랑 실제 코스 이름이 유니크하다는 말이었어.

**Comment by lameinthebox** [comment]
어느 쪽을 유니크 필드로 사용하느냐가 큰 문제가 아니니까 수정할게.

**Comment by holenet** [comment]
실제라는 말을 넣었으면 됬잖아
그리고 모든 강의를 크롤링 해본게 아니니까 장담할수는 없지

**Comment by lameinthebox** [comment]
오키
