### ISSUE TITLE
Multiple Crawler Task

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-backend#23]
When running multiple crawler task at the same time, two tasks have a chance to make an error like this,
```json
    {
        "id": 7,
        "status": "UNIQUE constraint failed: ttrs_course.name",
        "semester": "1학기",
        "started": "2018-05-08T23:47:43.643460+09:00",
        "year": "2016"
    }
```
It seems to be a kind of *race hazard*.
Should we limit the number of tasks running at the same time?

**Comment by lameinthebox** [comment]
It seems so. By the way, are there possible situations we might need multiple crawler instances at once?

**Comment by holenet** [comment]
Of course, running multiple crawling tasks is uncommon situation.
But it could be so in a situation like initial setup server's database, which we can avoid simultaneous excuting crawling by make crawling tasks manually.
Anyway, we might have to limit the number of running tasks.

**Comment by holenet** [comment]
~~### What should be done~~
~~- [ ] limit the number of running tasks.~~
  ~~- block creating crawling task request when another task is already running in the server machine.~~

**Comment by holenet** [comment]
It would be better to decide whether limit the number of running crawling task after the crawler's errors are completely debugged and we test the crawler again at server machine.

**Comment by lameinthebox** [comment]
I guess all bugs are fixed...?

**Comment by holenet** [comment]
When I run two crawlers at the same time, they seems to share the context of the file `crawler.py`...
```json
    {
        "id": 4,
        "status": "running: 교양 (학문의 기초-외국어) 18/29 total 59/36",
        "semester": "1학기",
        "started": "2018-05-09T18:37:55.444242+09:00",
        "year": "2018"
    },
    {
        "id": 5,
        "status": "running: 교양 (학문의 세계-문화와 예술) 2/3 total 60/36",
        "semester": "여름학기",
        "started": "2018-05-09T18:38:16.764743+09:00",
        "year": "2018"
    }
```

If you want to solve this problem, making class based crawling task would be a solution.

**Comment by holenet** [comment]
@lameinthebox 
The *global variable strategy* seems to have failed...
```json
{
    "id": 8,
    "status": "running: 교양 (학문의 기초-외국어) 4/6 total 49/25",
    "semester": "겨울학기",
    "year": "2017",
    "started": "2018-05-09T19:51:35.174781+09:00"
}
```
The total finished pages is more than the total pages.
I got this status EVEN IF I did not run crawlers simultaneously.
This accident happens when two crawlers run successively on the same process, which there is only one process on the development server.
<br><br>
```json
{
    "id": 9,
    "status": "running: 일선 1/2 total 37/32",
    "semester": "여름학기",
    "year": "2016",
    "started": "2018-05-09T20:02:05.993422+09:00"
}
```
Moreover, this has the same condition to above one.
BUT, I started the development server just before.
It seems to have occurred because of cases like that the pages of a `type` does not equal to sum of pages of each `field` in the `type`.
<br><br>
And... I'm sorry to say this, but there is another error.
```json
{
    "id": 10,
    "status": "string index out of range",
    "semester": "겨울학기",
    "year": "2017",
    "started": "2018-05-09T20:08:43.945827+09:00"
}
```
I run a crawler of "2017년 겨울학기", and the crawler got an error "string index out of range".
And the log of the crawler is here,
```
...
course: 주제탐구세미나 4 type: 전선 field: 
course: 주제탐구세미나 4 type: 전선 field: 
course: 고전탐구세미나 2 type: 전선 field: 
finished 전선
start running  일선
=====================일선 page 1/1=====================
string index out of range
```
I figured out the cause; the course's grade was empty.
And this code raised the error.
https://github.com/SWPP/ttrs-backend/blob/e58a53092103bb471f265fc291b63db9b38f4c6e/backend/manager/crawler.py#L346

<br><br>
_You_ guess all bugs are fixed...?
### **No**.

**Comment by lameinthebox** [comment]
Please see pr #42

**Comment by lameinthebox** [comment]
Closing issue as the corresponding pr is merged.
