### ISSUE TITLE
Running Crawler Task at the Server Machine

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-backend#25]
When I create a crawler task at the server machine, the server freezes sometimes.
Once the server freeze, I have to stop the development server and restart the server.
I think it is a matter of performance of AWS server(RAM, CPU, etc...).

In my opinion, there is an alternative; Run crawler task at another machine and send request to the server machine.
But, since this will result in replacing most of the existing codes, I afraid to do so.
Any other alternatives?

**Comment by lameinthebox** [comment]
Does the server machine freeze as well when there are only one or two crawler instances?

**Comment by holenet** [comment]
Yes.
I think this is because the server machine does not have sufficient resources to run two server; development server and deployment server.

**Comment by lameinthebox** [comment]
What about replacing server machine to one with higher performances when our project goes into orbit?

**Comment by holenet** [comment]
Do you have a _server machine with higher performances_?

**Comment by lameinthebox** [comment]
No. We can buy one.

**Comment by holenet** [comment]
No, **YOU** can buy one, not me.

**Comment by lameinthebox** [comment]
Closing issue as there exists no answer.
