### ISSUE TITLE
Should the Student have multiple 'my' time tables?

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-backend#30]
- Multiple 'my' time tables: make multiple 'my time table's for each semester.
- Only one 'my' time table: make only one 'my time table' regardless of the semester.
What is correct implementation?
Please give your opinions.

**Comment by Tommybro** [comment]
I think we need multiple 'my' time tables eventually.
But maybe it is okay to use only one 'my' time table for this project.
How about making multiple 'my' time tables if we have more left time.

**Comment by lameinthebox** [comment]
I think it is better to save the whole previous selected timetables since user might need it.

**Comment by holenet** [comment]
If we make multiple time tables, it would be better to make total 4 model classes for the time tables, like this,
- BaseTimeTable
- MyTimeTable
- BookmarkedTimeTable
- ReceivedTimeTable
The other three models will inherit BaseTimeTable.
<br>
<br>
BaseTimeTable will have these properties,
- owner
- type
- title
- memo
- lectures

<br>
<br>
And the other models will have more properties.

MyTimeTable
- year
- semester

BookmarkedTimeTable
- ?

ReceivedTimeTable
- sender

<br>
<br>
Is it right? (I'm not sure if the TimeTable should have year and semester for each TimeTables)

**Comment by lameinthebox** [comment]
If we don't put year and semester field in BookmarkedTT and ReceivedTT, are outdated bookmarkedtts and receivedtts going to be automatically deleted?

**Comment by holenet** [comment]
If they does not have year and semester field, the student have a set of bookmarked time tables and a set of received time tables regardless of the semester.
If they so, the student should be able to switch semesters to retrieve the past time tables.

**Comment by lameinthebox** [comment]
If there's no year and semester field, how can we provide semester-switching function?
By looking through lectures contained by tt?

**Comment by holenet** [comment]
I meant,
When the tables have year and semester field, the student will be able to switch semester.

**Comment by holenet** [comment]
I'm making time table serializers with 4 models (1 base model, 3 inheriting models).

**Comment by lameinthebox** [comment]
Closing issue as corresponding pr #45 is merged.
