### ISSUE TITLE
Which Authentication Method?

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-backend#32]
There is several authentication method in the Django rest framework such as,
- Basic Authentication
- Token Authentication
- Session Authentication
- Remote User Authentication
- Custom Authentication
- Etc...

Currently, our backend uses Basic Authentication, which is default authentication of rest framework.
But, in the point of security, [Basic Authentication](http://www.django-rest-framework.org/api-guide/authentication/#basicauthentication) is not proper choice.
In the same reason, [Token Authentication](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) also seems not good.

And [Session Authentication](http://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication) is good at security, but there might be some troubles when implementing for communication by *unsafe* methods(post, put, patch, delete).
We have to process the requests with **CSRF** tokens.

And [Remote User Authentication](http://www.django-rest-framework.org/api-guide/authentication/#remoteuserauthentication) and [Custon Authentication](http://www.django-rest-framework.org/api-guide/authentication/#customauthentication) seems more troublesome at the implementation.

So which one we should select for the authentication method?

**Comment by Tommybro** [comment]
Although there can be security problem, I think it will be better to use Basic Authentication like before as we don't know other Authentications well right now.
What about using other better authentications after we finish all the basic things if we have left time?

**Comment by holenet** [comment]
[django-rest-auth](https://github.com/Tivix/django-rest-auth) would be an alternative.
It's a third party package.

**Comment by Gamjae** [comment]
I don't think authentication method is important right now. It would be not late even we decide and implement certain auth method after we finish basic functions.

**Comment by holenet** [comment]
Okay, let's continue without changing authentication method.
I'll close this issue for now.
