### ISSUE TITLE
name 'tid' is not defined!!!

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-backend#38]
@lameinthebox 
There is an unresolved variable `tid`.
please check your code and resend pull request.
https://github.com/SWPP/ttrs-backend/blob/5c01fd0561f6036ebc1b6a325234a64237dac8e8/backend/manager/crawler.py#L111

**Comment by holenet** [comment]
In addition, there is no need to send the `detail` variable to `update` function because the `detail` variable is a global variable.
https://github.com/SWPP/ttrs-backend/blob/5c01fd0561f6036ebc1b6a325234a64237dac8e8/backend/manager/crawler.py#L30-L40

**Comment by lameinthebox** [comment]
I've made pull request #39.
Plus, I think it is better to leave update this way.
Doing so, we can easily move update function to crawler model.

**Comment by holenet** [comment]
Okay, I merged the pull request #39 .

**Comment by lameinthebox** [comment]
Closing issue as pr is merged.
