### ISSUE TITLE
Fields of TimeSlot Model for representing time points

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-backend#4]
`TimeSlot` model must contain information about starting and ending time point of the class.
More precisely, `TimeSlot` must contain day-of-week or the class and starting hour/minute and ending hour/minute.

Currently, `TimeSlot` model in `ttrs` app has two `DateTimeField` like below.
https://github.com/SWPP/ttrs-backend/blob/8646f2d124ed11e9c91437b9b63b35799fd2d3e6/backend/ttrs/models.py#L75-L77
This was because `DateTimeField` can wrap day-of-week, hour and minute in only one field.

But, I think `DateTimeField` will be troublesome in converting the field to a plane text, and vice versa.
And actually, `DateTimeField` is not efficient because it also contains redundant information such as year, month, day-of-month, second, etc...

So, an alternative implementation is here.
```python3
class TimeSlot(models.Model):
    day_of_week = models.CharField(max_length=10)
    start_time = models.CharField(max_length=10)
    end_time = models.CharField(max_length=10)
```
Just save data as plane data like `day_of_week = 'Monday'` or `end_time = '09:30'`.
Since `CharField` is just for a plane string data, it will be easier to use the fields than the current implementation.

However, changing data structure of a model makes more tasks to modify already implemented codes based on previous data structure.
If we are going to change the structure, it will be good to do as soon as possible.

~~**P.S.** I think we have to serperate `start_day` and `end_day` because there is a possibility of using this `TimeSlot` for recommendation of patial or complete timetable in after days.~~

**updated**
I decided not to separate day-of-week of starting and ending time point.
And I modified the implementation

**Comment by lameinthebox** [comment]
I think you've got a point. 그런데 이거 꼭 영어로 해야 하나요?

**Comment by lameinthebox** [comment]
그리고 start_day 와 end_day를 별개의 필드로 가지고 있는 것이 시간표 추천시에 어떠한 이점이 있을지 모르겠습니다. 예시를 하나만 들어주세요.

**Comment by holenet** [comment]
@lameinthebox
I thought a `TimeSlot` instance which have a period of two or more days can be useful for representing the area of a partial recommendation and even complete recommendation.
But, the new implementation cannot represent the area like "12:00-14:00 for all days of week".
So, I think we had better use a list of `TimeSlot` instance when making a recommendation query.

**Comment by holenet** [comment]
@lameinthebox 
I updated my comment of this issue

**Comment by lameinthebox** [comment]
ok
