### ISSUE TITLE
Does 'not_recommends' need when sign up?

### ISSUE THREAD

**Issue by Tommybro** [SWPP/ttrs-backend#40]
I think it will be better to get 'not_recommends' after sign in.
Is there any reason 'not_recommends' should be got from the user when sign up?
If there's no reason, please remove 'not_recommends' at student post api.

**Comment by holenet** [comment]
In fact, though you send a sign up request without param `not_recommends`, you would not get any errors and the `not_recommends` field of the new student would be empty set.
So, you don't have to update backend code just send sign up request omitting `not_recommends`.
I will modify the content of the Wiki; set requirement of `not_recommends` field to 'X'.
