### ISSUE TITLE
Question about sign up

### ISSUE THREAD

**Issue by Tommybro** [SWPP/ttrs-backend#41]
I passed studentInfo to ttrs/students/signup to post new student from frontend.
```
studentInfo = {
  username: "user3",
  password: "qwer1234",
  email: "user3@snu.ac.kr",
  grade: 1,
  college: 1,
  department: null,
  major: null,
}
```
But I got 400 bad request from backend without explicit error message.
Do you know any reason why I got 400 bad request?
* For all I know, 'not_recommends' doesn't need to be passed to backend . It will be void list*

**Comment by holenet** [comment]
Please refer to the [section](https://github.com/SWPP/ttrs-backend/wiki/RESTful-API-Specification%3A-Student#request--response-example) of the WIKI
You can see how to **construct** request data and what the **common error** are.

If you send a request with that data to the backend directly in your hand, it will be clear why you have got *400 bad request*. And that is already described error at the WIKI.

**p.s.**
You can represent **code** by tag ` ``` `

**Comment by Tommybro** [comment]
I passed studentInfo again from the frontend.
 ```
studentInfo = {
   username: "user4",
   password: "qwer1234",
   email: "user4@snu.ac.kr",
   grade: 3,
   college: 8,
   department: 25,
   major: null
}
```
But I got 400 bad request again. So I send a request with this data to the backend directly in my hand.
Backend gave me error saying "JSON parse error - Expecting property name enclosed in double quotes"
It means username should be "username" and so on..
Can you make it possible to sign up when I pass username not "username"??

**p.s.**
If I change username to "username" and so on, backend gives me 201 Created Respoonse for same studentInfo above.

**Comment by holenet** [comment]
Uh... Did you send that code as it is, including `studentInfo`??
`studentInfo` is not valid *key* on the *sign up*.
Also, `=` is not valid expression of *JSON*.
And, *JSON* does not support string that is not in double quotes.
You seems not to get the concept of *JSON* properly.

The data you uploaded is the representation of *dictionary* at *js*.
*js* does not use double quoted string *key*.
But, if you send a JSON request in the *js* app, the *js* app will automatically convert the keys to string expression with double quotes, which is valid expression of string key in *JSON*.

**Comment by Tommybro** [comment]
I sent studentInfo *dictionary*.
And studentInfo's value is
```
{
   username: "user4",
   password: "qwer1234",
   email: "user4@snu.ac.kr",
   grade: 3,
   college: 8,
   department: 25,
   major: null
}
```

**Comment by holenet** [comment]
So what?

**Comment by Tommybro** [comment]
So got 400 BAD REQUEST
I will try not to send studentInfo.
If it succeed, I'll let you know

**Comment by holenet** [comment]
YOU CANNOT SEND DATA WITH KEYS NOT IN DOUBLE QUOTES TO THE BACKEND

**Comment by holenet** [comment]
Why do you try not to send `studentInfo`?
Even if `studentInfo` has keys not in double quotes, the `js` app will convert to keys in double quotes.
So, the backend will receive valid data of *JSON*.

**Comment by Tommybro** [comment]
Then what is the reason I got bad request?

**Comment by holenet** [comment]
Just try to send this data(with double quotes) to the backend directly.
```json
{
   "username": "user4",
   "password": "qwer1234",
   "email": "user4@snu.ac.kr",
   "grade": 3,
   "college": 8,
   "department": 25,
   "major": null
}
```
And then, you will receive error detail message.

**Comment by Tommybro** [comment]
그거 해봤는데 201 Created Respoonse 받았다고요

**Comment by holenet** [comment]
Good!

**Comment by holenet** [comment]
It is not a problem of backend-frontend communication.
Just problem of frontend.

**Comment by Tommybro** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by holenet** [comment]
@Tommybro Could you reopen the issue at the frontend?
