### ISSUE TITLE
There are Lectures without any time slots (Crawler does not die!)

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-backend#46]
I was calculating the number of whole cases of constructing time table, and I checked the number of lectures of a time table. There, I found a time table with lectures more than 50!!!
I recognized something is wrong, then I figured out that there are lectures which have no time slots.
I have thought lectures of this case are filtered out at the crawler stage, but aren't in real.
And, there was so many lectures with this condition!
I searched at 'sugang.snu.ac.kr' and I confirmed we were crawling lectures not having time slots, like below,
![image](https://user-images.githubusercontent.com/24453019/39902114-54b62548-5507-11e8-96f3-ba19a3b6440c.png)

**Comment by Gamjae** [comment]
Can you list more lecture that don't have time slot?
I guess those are flexible in time

**Comment by holenet** [comment]
@Gamjae What do you mean "flexible in time"?

**Comment by Gamjae** [comment]
@holenet I mean if someone takes one of those lectures, he or she can choose any empty time slots.
I don't know about other lectures, but I've heard Musical College students should take practice lessons on their instruments and those don't have fixed schedule

**Comment by holenet** [comment]
Um... yes, you are right, but we already discussed with this lectures and we decided to just do not collect those lectures, but I found lectures without time slots in the database. It is just implementation error.

**Comment by lameinthebox** [comment]
It surely is different from what we've intended, but how about just leaving it this way?
I think saving lectures that don't have fixed time slots would bring ttrs more flexibility and is necessary for some departments such as Music Department (as @Gamjae described.)
If leaving our crawler this way might cause any kind of side effects (like rewriting other parts of our code such as models), I'll fix the crawler, but if not, I think it is better this way.
How do you think about it @holenet?

**Comment by holenet** [comment]
If you want to do so, you have to modify the `crawler` so that the crawler can collect ALL lectures regardless of existance of time slots.

**Comment by lameinthebox** [comment]
Sure I'll handle it.

**Comment by lameinthebox** [comment]
I think our crawler is already collecting all the lectures including ones without any timetable properly since it iterates over timeslots after the lecture instance is created.

**Comment by holenet** [comment]
@lameinthebox
okay, I'll check.

**Comment by holenet** [comment]
Good!
There are all lectures without a single exception.
I'll close this issue
