### ISSUE TITLE
Can you implement that course has lecture list?

### ISSUE THREAD

**Issue by Tommybro** [SWPP/ttrs-backend#47]
At 'courses/', I want to get lecture list from each course.
Can you?

**Comment by holenet** [comment]
Do you want to get **id**s of lectures?

**Comment by Tommybro** [comment]
I want to get all information of lectures which I can get at `lectures/<int:pk>/ `

**Comment by Tommybro** [comment]
Please do like `college/` (college includes all information of departments).

**Comment by holenet** [comment]
Could I know why you want to get so detailed information?

**Comment by Tommybro** [comment]
I will show lecture info to user when user searchs lecture.
I will get all information of lectures and courses when user sign in, and then whenver it nees, I will use those information (I don't want to communicate with backend whenever I needs lecture information).

**Comment by holenet** [comment]
I don't think getting all lectures and courses and save at frontend is good approach.
There are thousands of lectures and courses in every year and semester.
Receiving these data might be quite slow, which leads low performance.
Could you consider dynamically loading lectures and courses like 'sugang.snu.ac.kr'?

**Comment by Tommybro** [comment]
But when we search,  we should check all courses. Isn' it?
And then, we should show user lectures of those courses.
I think that if each course has lecture list, we can implement searching easier.

**Comment by holenet** [comment]
Searching algorithm is already implemented by Django, and we already use the filter feature as `FilterAPIView`. So you can search with certain params in simple way. The specification is described at the [WIKI: API Specification](https://github.com/SWPP/ttrs-backend/wiki/RESTful-API-Specification%3A-Lecture#request--response-example).
But the _Request & Response Example_ is deprecated; they became more detailed, became able to represent the corresponding course and the corresponding time slots properly.

I add an example of newest version of backend.

**Request**
```json
GET /ttrs/lectures/?course__name__startswith=디자인과&course__name__endswith=문화
```
**Response**
```json
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "id": 3500,
        "course": {
            "id": 1808,
            "code": "611.2006A",
            "name": "디자인과 문화",
            "type": "전선",
            "field": "",
            "grade": 2,
            "credit": 3,
            "college": 4,
            "department": 30,
            "major": 15
        },
        "time_slots": [
            {
                "id": 5783,
                "classroom": {
                    "id": 230,
                    "building": "049",
                    "room_no": "322"
                },
                "day_of_week": "월",
                "start_time": "14:00",
                "end_time": "16:50"
            }
        ],
        "year": 2018,
        "semester": "1학기",
        "number": "001",
        "instructor": "김민수",
        "note": ""
    },
    {
        "id": 6892,
        "course": {
            "id": 1808,
            "code": "611.2006A",
            "name": "디자인과 문화",
            "type": "전선",
            "field": "",
            "grade": 2,
            "credit": 3,
            "college": 4,
            "department": 30,
            "major": 15
        },
        "time_slots": [
            {
                "id": 10825,
                "classroom": {
                    "id": 230,
                    "building": "049",
                    "room_no": "322"
                },
                "day_of_week": "월",
                "start_time": "14:00",
                "end_time": "16:50"
            }
        ],
        "year": 2017,
        "semester": "2학기",
        "number": "001",
        "instructor": "김민수",
        "note": ""
    }
]
```

I think this representation represents all information of the lecture instance.

**Comment by Tommybro** [comment]
OK
