### ISSUE TITLE
Sign up error

### ISSUE THREAD

**Issue by Tommybro** [SWPP/ttrs-backend#48]
I tried to sign up from the frontend but I got 500 internal server error.
So I tried to sign up from the backend but I got `OperationalError at /ttrs/students/signup/`
This happens after I pull upstream dev right before.
Please check sign up works well.

**Comment by holenet** [comment]
please write whole error message.

**Comment by holenet** [comment]
I tried to sign up from the backend API and it did work well.
So, It seems to be an error caused by tangled migrations.
For the specification, please mention with the detail of the error.

**Comment by Tommybro** [comment]
I pulled upstream dev but when I try to migrate, I got error.
I attatch error picture.
![kakaotalk_20180512_011147870](https://user-images.githubusercontent.com/19183069/39953774-4e1384f6-55a2-11e8-811f-e470a8a20b36.jpg)

**Comment by holenet** [comment]
You had better to reset all things related to migrations.

**How reset migrations**
1. Remove _migrations_ directory of each app. (in this case, _ttrs_ and _manager_)
2. Remove database file. (in this case, _db.sqlite3_)
3. make migrations for each app.
```console
python3 manage.py makemigrations ttrs
python3 manage.py makemigrations manager
python3 manage.py makemigrations
```
4. migrate
```console
python3 manage.py migrate
```

I think this process will clear previous migration environment. Try it, and let me know the result.
I hope you do not get any error this time.

**Comment by Tommybro** [comment]
I think it works well as I did what you said.
Thanks
