### ISSUE TITLE
Permission of StudentLIst

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-backend#50]
Currently, the permission of StudentList is authenticated user only.
But, I think we should prevent the students from retrieving other students.
As a result, StudentList would become unnecessary view or should be accessed by admin users only.
So, it would be better to alter the permission of StudentList to admin user only.

**Comment by lameinthebox** [comment]
I agree. It would be a minor fix, so I think you can directly edit it.

**Comment by holenet** [comment]
I changed the code directly on [commit](https://github.com/SWPP/ttrs-backend/commit/ddef4317d2067591680080035885ce83ffa93b6d)
