### ISSUE TITLE
Request for modification of my-time-tables post api

### ISSUE THREAD

**Issue by Tommybro** [SWPP/ttrs-backend#53]
When I tried to add only one lecture '초급중국어 2' whose instructor is '김지영', I got 400 bad request saying overlap of timeslots.
I think it's due to this lecture itself have overlapped timeslots whose classroom is different.
Please solve this problem.

**Comment by holenet** [comment]
Please specify year and semster of the lecture

**Comment by holenet** [comment]
I don't think this is an IMPORTANT issue, it is just a simple error.

**Comment by holenet** [comment]
When you write a bug report, you have to make clear on describing the condition the error occurred in.

**Comment by Tommybro** [comment]
2018 year
1학기 semester
Sorry

**Comment by holenet** [comment]
Thanks for reporting this bug, I'll fix it.

**Comment by holenet** [comment]
Resolved.
