### ISSUE TITLE
Please make api which gives semester list

### ISSUE THREAD

**Issue by Tommybro** [SWPP/ttrs-backend#59]

**Comment by holenet** [comment]
Shui roon daeng?

**Comment by holenet** [comment]
@Tommybro 
Which structure do you want to receive?
Please show me some examples.

**Comment by Tommybro** [comment]
['2018-S', '2018-1', '2017-W', '2017-2', '2017-S', '2017-1']

**Comment by holenet** [comment]
Why don't you get year and semester separately?

**Comment by Tommybro** [comment]
Shi roon daeng?

**Comment by Tommybro** [comment]
Then, give me
option = [
  {
    year: 2018
    semester: '여름학기'
  }
  ...
]

**Comment by holenet** [comment]
What is `option`?
`option = ` is not valid JSON representation.

**Comment by Tommybro** [comment]
No meaning.
give me array of dictionaries.

**Comment by holenet** [comment]
Okay

**Comment by lameinthebox** [comment]
What for?

**Comment by holenet** [comment]
@lameinthebox For _SemesterSwitch_.
Front have to be able to switch semester(including year).
So, frontend should get semester list from backend.

**Comment by lameinthebox** [comment]
Closing issue as corresponding pull request #60 is merged.
