### ISSUE TITLE
About send TimeTable

### ISSUE THREAD

**Issue by Tommybro** [SWPP/ttrs-backend#64]
I think that user can not send timetable to himself.
When user tries to send timetable to himself, please show 400 bad request response

**Comment by holenet** [comment]
Why do you think so?
There would be no problem even if a student is able to send his timetable to himself.

**Comment by Tommybro** [comment]
I thought that there is no reason user send timetable to himself because we provide bookmark service to user.

**Comment by holenet** [comment]
Yes, _sending timetable to me_ feature is definitely redundant, but I also think blocking that feature would be redundant works.

**Comment by Tommybro** [comment]
I said this because It will be convenient for me to implement Receive Tab :)

**Comment by Tommybro** [comment]
But you don't need to block sending time table to himself

**Comment by holenet** [comment]
If you want to block that feature, you can do it yourself.
