### ISSUE TITLE
Progress Report: Iteration 3

### ISSUE THREAD

**Issue by lameinthebox** [SWPP/ttrs-backend#69]
# Features implemented in this iteration

## Backend
- **Email Verification**
  Whenever a student signs up, backend automatically sends a confirmation email.
  * by **권현우**
    - related issues: 
    - related pull requests: #62 
- **Continuous Integration**
  Implemented coverage tests for django apps using `Travis CI`.
  * by **권현우**
    - related issues:
    - related pull requests: #65 
- **Improvement on recommender**
   Implemented recommend method using a basic `branch and bound` algorithm.
  * by **남예현**
    - related issues:
    - related pull requests: #67 
## Frontend
- **BookmarkedTimetableTab organism**
  * by **김성재**
    - related issues:
    - related pull requests: [#20](https://github.com/SWPP/ttrs-frontend/pull/20) [#25](https://github.com/SWPP/ttrs-frontend/pull/25)
- **ReceivedTimetableTab organism**
  * by **김성재**
    - related issues:
    - related pull requests: [#25](https://github.com/SWPP/ttrs-frontend/pull/25)
- **SettingsTab organism**
  * by **김성재**
    - related issues:
    - related pull requests: [#25](https://github.com/SWPP/ttrs-frontend/pull/25)
- **Timetable molecule, Lecture Popup molecule**
  * by **김성재**
    - related issues: [#26](https://github.com/SWPP/ttrs-frontend/issues/26)
    - related pull requests:  [#25](https://github.com/SWPP/ttrs-frontend/pull/25)
  * by **남예현**
    - related issues:
    - related pull requests: [#19](https://github.com/SWPP/ttrs-frontend/pull/19) [#24](https://github.com/SWPP/ttrs-frontend/pull/24)
# Test results
## Backend
![screenshot from 2018-05-29 02-57-13](https://user-images.githubusercontent.com/19164119/40625213-08160076-62ec-11e8-8b0c-52fe81839c53.png)

**Comment by holenet** [comment]
Close outdated
